services:
  - type: web
    name: churn-api
    env: docker
    plan: free
    repo: https://github.com/tuusuario/mlops-churn
    branch: main
    rootDir: serving
    dockerfilePath: Dockerfile
    autoDeploy: true

